services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  redisapi:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redisnginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "4052:4052"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - redisapi

volumes:
  redis_data:
